name: Build Geometry Dash DS

  on:
    push:
      branches: [ main, master ]
    pull_request:
      branches: [ main, master ]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup devkitPro
          uses: devkitpro/setup-devkitpro@v1
          with:
            devkitpro-version: 'latest'

        - name: Run make
          run: make

        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: geometrydash-nds
            path: geometrydash.nds
